opam-version: "2.0"
maintainer: "Robur <team@robur.coop>"
authors: ["Robur <team@robur.coop>"]
homepage: "https://github.com/robur-coop/immuable"
dev-repo: "git+https://github.com/robur-coop/immuable.git"
bug-reports: "https://github.com/robur-coop/immuable/issues"
license: "MIT"

depends: [
  "ocaml" {>= "5.3.0"}
# As we don't install `dune-package` file
  "dune" {>= "3.0.0" & build}
  "vif"
  "mirage-crypto-rng-mkernel"
  "vifu"
  "gmp"
  "progress"
  "flux"
  "mnet" {>= "0.0.7"}
  "carton" {>= "1.3.0"}
  "unic" {build}
  "mfetch" {build}
  "art"
  "encore"
  "cattery"
  "mcrunch"
]
build: [
  [make "all"]
]
synopsis: "An unikernel which serve HTTP contents"
pin-depends: [
  [ "zarith.dev" "git+https://github.com/mirage/Zarith.git#df8969d9bb95cffca13e31a615189ab27ada0684" ]
]
x-mkernel-pre-build: [
  ["mfetch" "fetch" "--with-dune-file" "--file=_mfetch"]
  ["mfetch" "lock" "--file=_mfetch" "--output=_mfetch.locked"]
]
