opam-version: "2.0"
maintainer: "Robur <team@robur.coop>"
authors: ["Robur <team@robur.coop>"]
homepage: "https://github.com/robur-coop/immuable"
dev-repo: "git+https://github.com/robur-coop/immuable.git"
bug-reports: "https://github.com/robur-coop/immuable/issues"
license: "MIT"

depends: [
  "ocaml" {>= "5.3.0"}
  "dune" {>= "3.0.0"}
  "vif"
  "mirage-crypto-rng-mkernel"
  "vifu"
  "progress"
  "flux"
  "carton" {>= "1.3.0"}
  "art"
  "encore"
  "cattery"
  "mcrunch"
]
build: [
  [make "all"]
]
synopsis: "An unikernel which serve HTTP contents"
pin-depends: [
  [ "zarith.dev" "git+https://github.com/mirage/Zarith.git#df8969d9bb95cffca13e31a615189ab27ada0684" ]
  [ "unic.dev" "git+https://git.robur.coop/robur/unic.git#b2188d2da50c72e58dfc14bb5578e7e35d1e5311" ]
  [ "mfetch.dev" "git+https://git.robur.coop/robur/mfetch.git#33204acd6cc597530d1cff7785503a7de6a0c799" ]
]
